version: '3'
services:
    mysql:
      image: mysql
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
      volumes:
        - ./database/init:/docker-entrypoint-initdb.d/:ro